### ISSUE TITLE
Missing certifi packge

### ISSUE THREAD

**Issue by nathanlin24** [HewlettPackard/python-ilorest-library#110]
I tried the set_uid_light example and it failed  to import the _certifi_ module. It works after I pip installed the module. Perhaps it needs to be added back to the requirement file?

Example script at first fails execute with the following error:
```
(test_pip) [w@centos8vm Redfish]$ python set_uid_light.py 
Traceback (most recent call last):
  File "set_uid_light.py", line 23, in <module>
    from redfish import RedfishClient
  File "/home/w/test_pip/lib64/python3.6/site-packages/redfish/__init__.py", line 7, in <module>
    from redfish.rest.v1 import AuthMethod, LegacyRestClient, RedfishClient
  File "/home/w/test_pip/lib64/python3.6/site-packages/redfish/rest/v1.py", line 27, in <module>
    from redfish.rest.connections import Blobstore2Connection, HttpConnection, InvalidCredentialsError
  File "/home/w/test_pip/lib64/python3.6/site-packages/redfish/rest/connections.py", line 24, in <module>
    import certifi
ModuleNotFoundError: No module named 'certifi'
(test_pip) [w@centos8vm Redfish]$ pip list
Package                Version
---------------------- -------
decorator              5.0.7
jsonpatch              1.32
jsonpath-rw            1.4.0
jsonpointer            2.1
pip                    21.1.1
ply                    3.11
python-ilorest-library 3.2.1
setuptools             39.2.0
six                    1.15.0
urllib3                1.26.4
(test_pip) [w@centos8vm Redfish]$ python --version
Python 3.6.8
(test_pip) [w@centos8vm Redfish]$ 
```

After adding the certifi module it works:
```
(test_pip) [w@centos8vm Redfish]$ pip install certifi
Collecting certifi
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Installing collected packages: certifi
Successfully installed certifi-2020.12.5
(test_pip) [w@centos8vm Redfish]$ python --version
Python 3.6.8
(test_pip) [w@centos8vm Redfish]$ pip list
Package                Version
---------------------- ---------
certifi                2020.12.5
decorator              5.0.7
jsonpatch              1.32
jsonpath-rw            1.4.0
jsonpointer            2.1
pip                    21.1.1
ply                    3.11
python-ilorest-library 3.2.1
setuptools             39.2.0
six                    1.15.0
urllib3                1.26.4
(test_pip) [w@centos8vm Redfish]$ python set_uid_light.py 
	Found resource directory at /redfish/v1/resourcedirectory

Current Indicator LED Status: 'Lit'

Will extinguish indicator LED.

Success!

{
    "error": {
        "@Message.ExtendedInfo": [
            {
                "MessageId": "Base.1.4.Success"
            }
        ],
        "code": "iLO.0.10.ExtendedInfo",
        "message": "See @Message.ExtendedInfo for more information."
    }
}

Updated Indicator LED Status: 'Off'
```

**Comment by rajeevkallur** [comment]
Added certifi to requirements.txt
