### ISSUE TITLE
'RestObject' object has no attribute 'rest_client'

### ISSUE THREAD

**Issue by encore133** [HewlettPackard/python-ilorest-library#21]
When I ran ex10_add_ilo_user_account.py on DL380 Gen10 server, i got below error.
Could you help me to figure out what did I miss here? 

```
Traceback (most recent call last):
  File "C:/Users/lenovo/PycharmProjects/untitled1/ilo5_test.py", line 43, in <module>
    REST_OBJ = RestObject(iLO_https_url, iLO_account, iLO_password)
  File "C:\Users\lenovo\PycharmProjects\untitled1\_restobject.py", line 88, in __init__
    default_prefix="/rest/v1")
  File "C:\Python27\lib\site-packages\redfish\rest\v1.py", line 1489, in rest_client
    sessionkey=sessionkey, is_redfish=is_redfish, cache=cache)
  File "C:\Python27\lib\site-packages\redfish\rest\v1.py", line 1531, in get_client_instance
    is_redfish=is_redfish, cache=cache)
  File "C:\Python27\lib\site-packages\redfish\rest\v1.py", line 1114, in __init__
    self.login_url = self.root.links.Sessions.href
KeyError: 'links'
Exception AttributeError: "'RestObject' object has no attribute 'rest_client'" in <bound method RestObject.__del__ of <_restobject.RestObject object at 0x05AD2E10>> ignored

Process finished with exit code 1
```

Here's the version I have:

```
C:\Users\lenovo>pip2 show python-ilorest-library
Name: python-ilorest-library
Version: 2.2.0
Summary: iLO Rest Python Library
Home-page: https://github.com/HewlettPackard/python-ilorest-library
Author: Hewlett Packard Enterprise
Author-email: kocurek@hpe.com
License: UNKNOWN
Location: c:\python27\lib\site-packages
Requires: jsonpatch, jsonpath-rw, jsonpointer, validictory, urlparse2, six

```

**Comment by Yergidy** [comment]
The object "RestObject" is for iLO 4, non-redfish servers. For iLO 5 and servers with redfish, the object "RedfishObject" is the one you should be using.

**Comment by karthikvrsjp** [comment]
I am running the code for iLO 4 on m510 server and getting this error.. 
AttributeError: 'RestObject' object has no attribute 'rest_client'


Full log:
[root@splunksetup01 Rest]# python3.6 ex16_computer_details.py
Started..!
Trying to get REST object..!
In init function of RestObject
Traceback (most recent call last):
  File "ex16_computer_details.py", line 107, in <module>
    REST_OBJ = RestObject(iLO_https_url, iLO_account, iLO_password)
  File "/home/karthikvr/PYTHON_iLO_REST/python-ilorest-library-master/examples/Rest/_restobject.py", line 90, in __init__
    username=login_account, password=login_password)
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line 1231, in get_client_instance
    is_redfish=is_redfish, cache=cache, proxy=proxy)
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line 445, in __init__
    self.get_root_object()
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line 590, in get_root_object
    "return code: %d" % resp.status)
redfish.rest.v1.ServerDownOrUnreachableError: Server not reachable, return code: 404
Exception ignored in: <bound method RestObject.__del__ of <_restobject.RestObject object at 0x7f9a632939e8>>
Traceback (most recent call last):
  File "/home/karthikvr/PYTHON_iLO_REST/python-ilorest-library-master/examples/Rest/_restobject.py", line 98, in __del__
    self.rest_client.logout()
AttributeError: 'RestObject' object has no attribute 'rest_client'


Can you please let me know the resolution? Many thanks in advance.
