### ISSUE TITLE
error importing restobject 

### ISSUE THREAD

**Issue by bihary84** [HewlettPackard/python-ilorest-library#3]
When i try to import the restobject I got anerror message.
Could you help me to figure out what did I miss here?

This is how I import it:
`from _restobject import RestObject`

This is the error message:

```
raceback (most recent call last):
  File "./ilo.py", line 18, in <module>
    from _restobject import RestObject
ImportError: No module named '_restobject'
```

I installed the ilorest library as well:

```
pip install python-ilorest-library
Collecting python-ilorest-library
  Downloading python-ilorest-library-1.9.2.zip (78kB)
    100% |████████████████████████████████| 81kB 129kB/s
Collecting jsonpatch (from python-ilorest-library)
  Downloading jsonpatch-1.16-py2.py3-none-any.whl
Collecting jsonpath_rw (from python-ilorest-library)
  Downloading jsonpath-rw-1.4.0.tar.gz
Collecting jsonpointer (from python-ilorest-library)
  Downloading jsonpointer-1.10.tar.gz
Collecting validictory (from python-ilorest-library)
  Downloading validictory-1.1.1.tar.gz
Collecting urlparse2 (from python-ilorest-library)
  Downloading urlparse2-1.1.1.tar.gz
Collecting ply (from jsonpath_rw->python-ilorest-library)
  Downloading ply-3.10.tar.gz (150kB)
    100% |████████████████████████████████| 153kB 283kB/s
Collecting decorator (from jsonpath_rw->python-ilorest-library)
  Downloading decorator-4.0.11-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/lib/python3.4/site-packages (from jsonpath_rw->python-ilorest-library)
Collecting recordtype (from urlparse2->python-ilorest-library)
  Downloading recordtype-1.1.tar.gz
Building wheels for collected packages: python-ilorest-library, jsonpath-rw, jsonpointer, validictory, urlparse2, ply, recordtype
  Running setup.py bdist_wheel for python-ilorest-library ... done
  Stored in directory: /root/.cache/pip/wheels/f6/09/94/270372428edee741558a548a2b376ff93fc1391f7f6b7026b8
  Running setup.py bdist_wheel for jsonpath-rw ... done
  Stored in directory: /root/.cache/pip/wheels/ff/80/3d/6d630248dd938306a8691b9658ee91e07fb794076d714f8ce8
  Running setup.py bdist_wheel for jsonpointer ... done
  Stored in directory: /root/.cache/pip/wheels/c6/63/b3/64aa830fca63497c9098d7a7b08058d261f7709727c7d93767
  Running setup.py bdist_wheel for validictory ... done
  Stored in directory: /root/.cache/pip/wheels/ae/96/32/1e175a036b68889ac08b1802219618bea8a3a020e376e3bc98
  Running setup.py bdist_wheel for urlparse2 ... done
  Stored in directory: /root/.cache/pip/wheels/d0/08/0e/1bb071cd176e00fcbc1dc7aba3e0f649b4f54c0e8c3203c7ac
  Running setup.py bdist_wheel for ply ... done
  Stored in directory: /root/.cache/pip/wheels/ad/dd/ad/8ce1991a7b380dfe23d6cc81a4de5c2775bc728b5a0a7721aa
  Running setup.py bdist_wheel for recordtype ... done
  Stored in directory: /root/.cache/pip/wheels/0e/52/54/c5f783e96e2b1f5364d360716b47768c21d84efa73d3745b45
Successfully built python-ilorest-library jsonpath-rw jsonpointer validictory urlparse2 ply recordtype
Installing collected packages: jsonpointer, jsonpatch, ply, decorator, jsonpath-rw, validictory, recordtype, urlparse2, python-ilorest-library
Successfully installed decorator-4.0.11 jsonpatch-1.16 jsonpath-rw-1.4.0 jsonpointer-1.10 ply-3.10 python-ilorest-library-1.9.2 recordtype-1.1 urlparse2-1.1.1 validictory-1.1.
```

**Comment by LumbaJack** [comment]
@bihary84 _restobject.py is a file we created to help with the examples. You can download it here: https://github.com/HewlettPackard/python-ilorest-library/blob/master/examples/Redfish/_redfishobject.py

**Comment by bihary84** [comment]
Hi Jack!
Thank you, I had the impression this is inside  the library.
I downloaded it but not I got this error message:

```
python ex10_add_ilo_user_account.py
Traceback (most recent call last):
  File "ex10_add_ilo_user_account.py", line 16, in <module>
    from _redfishobject import RedfishObject
  File "/root/python/_redfishobject.py", line 74, in <module>
    import redfish.ris.tpdefs
ImportError: No module named redfish.ris.tpdefs

```

**Comment by bihary84** [comment]
I am using this:
https://github.com/HewlettPackard/python-ilorest-library

I just ran the pip install to obtain the library as you can see above. 
I have this version:
```
pip3 show python-ilorest-library
Name: python-ilorest-library
Version: 1.9.2
Summary: iLO Rest Python Library
Home-page: https://github.com/HewlettPackard/python-ilorest-library
Author: Hewlett Packard Enterprise
Author-email: jackgarcia77@gmail.com
License: UNKNOWN
Location: /usr/lib/python3.4/site-packages
Requires: validictory, jsonpath-rw, jsonpatch, jsonpointer, urlparse2
```
Should I do the install in a different way? Or are there any prerequisite?

**Comment by LumbaJack** [comment]
@bihary84 installing from source is usually my recommendation. Also keep in mind that this library doesn't have support for python 3.

**Comment by bihary84** [comment]
I see. In that case I will try to manually put together the rest calls.

**Comment by LumbaJack** [comment]
@bihary84 you may want to see if the manually installation works. Just download the zip file and run "python setup.py install". Also we are working on releasing official support for python 3 in the next 2 months.

**Comment by bihary84** [comment]
I need python3 so if this is not supported I cannot use that. Actually, I created the python calls I need during this afternoon.  I just needed to obtain/delete a token and create/list/del users. 
Though, it was a bit tricky to figure out the calls based on the available documentation but finally i managed it:)
Thank you for your help!
How can I be notified about the next released which supports the python3?

**Comment by LumbaJack** [comment]
It will be in our 2.0.2+ release. To keep up with releases you can watch/start the project.

**Comment by bihary84** [comment]
Thank you! I started to watch the project!

**Comment by tbarbette** [comment]
This file is still not distributed out of today's "pip install". Therefore the quick start example still does not work if followed "line by line".
