### ISSUE TITLE
ISSUE #error on #from get_resource_directory import get_resource_directory

### ISSUE THREAD

**Issue by Yasinmohammed007** [HewlettPackard/python-ilorest-library#75]
Hi,

I've cloned this and yet i see an issue with importing lines

from get_resource_directory import get_resource_directory

i have tried to run reboot_server. py

got this error.

at output
++++++++++++++++++++++++++++++++++++++++++++++++++++=
Traceback (most recent call last):
  File "C:/Users/503144060/PycharmProjects/python-ilorest-library-master/examples/Redfish/reboot_server.py", line 97, in <module>
    reboot_server(REDFISHOBJ)
	Found resource directory at /redfish/v1/resourcedirectory
  File "C:/Users/503144060/PycharmProjects/python-ilorest-library-master/examples/Redfish/reboot_server.py", line 44, in reboot_server

    systems_members_response = _redfishobj.get(systems_uri)
UnboundLocalError: local variable 'systems_uri' referenced before assignment

**Comment by topritchett** [comment]
We just updated the script.
Would you try using the updated reboot_server.py?

**Comment by rajeevkallur** [comment]
Example scripts are updated
