### ISSUE TITLE
Error message when executing get_LogicalDrives.py

### ISSUE THREAD

**Issue by Korschenbroich** [HewlettPackard/python-ilorest-library#89]
I did try to run "get_LogicalDrives.py", but get the following error messages:

```
/PycharmProjects/python-ilorest-library/examples/Redfish/get_LogicalDrives.py
	Found resource directory at /redfish/v1/resourcedirectory

Traceback (most recent call last):
  File "C:/Users/MichaelMader(MECSwar/PycharmProjects/python-ilorest-library/examples/Redfish/get_LogicalDrives.py", line 99, in <module>
    get_SmartArray_LogicalDrives(REDFISHOBJ)
  File "C:/Users/MichaelMader(MECSwar/PycharmProjects/python-ilorest-library/examples/Redfish/get_LogicalDrives.py", line 50, in get_SmartArray_LogicalDrives
    smartstorage_response = _redfishobj.get(smartstorage_uri).obj['Members']
KeyError: 'Members'

Process finished with exit code 1
```

Other examples (e. g. "get_SmartArray_EncryptionSettings.py") are working fine.
Any idea how I could fix the problem?

Thank sand regards,
Michael

**Comment by rajeevkallur** [comment]
Fixed
