### ISSUE TITLE
SEGFAULT while trying to read odata

### ISSUE THREAD

**Issue by tbabamuratov** [HewlettPackard/python-ilorest-library#93]
While running an application using the python API we ran into the following error segfault error.

I tried to get the source code of the library for further analysis but I couldn't find any useful data

python code in use
```python
try:
    import redfish
    from redfish import RedfishClient
    from redfish.rest.v1 import ServerDownOrUnreachableError
except Exception as e:
    logger.error("redfish not installed")
    # "pip3 install python-ilorest-library"


def get_resource_directory(redfishobj):
    try:
        resource_uri = redfishobj.root.obj.Oem.Hpe.Links.ResourceDirectory['@odata.id']
    except (KeyError, AttributeError):
        logger.exception("Resource directory is only available on HPE servers")
        return None
    response = redfishobj.get(resource_uri)
    resources = []
    if response.status == 200:
        resources = response.dict["Instances"]
    else:
        logger.exception("Resource directory missing at /redfish/v1/resourcedirectory")
    return resources
```

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/python3.6 /dn/python/my_agent/sys_info.py'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f663f1b3f97 in ChifSec_PrepareSendPacket () from /usr/lib/x86_64-linux-gnu/ilorest_chif.so
[Current thread is 1 (Thread 0x7f664ad96740 (LWP 3140))]
(gdb) bt
#0  0x00007f663f1b3f97 in ChifSec_PrepareSendPacket () from /usr/lib/x86_64-linux-gnu/ilorest_chif.so
#1  0x00007f663f1b2e91 in SendPacket () from /usr/lib/x86_64-linux-gnu/ilorest_chif.so
#2  0x00007f663f1b30c9 in PacketExchange () from /usr/lib/x86_64-linux-gnu/ilorest_chif.so
#3  0x00007f663f1b3503 in ChifPacketExchangeSpecifyTimeout () from /usr/lib/x86_64-linux-gnu/ilorest_chif.so
#4  0x00007f6646f96dae in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#5  0x00007f6646f9671f in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#6  0x00007f66471aaba4 in _ctypes_callproc () from /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so
#7  0x00007f66471ab223 in ?? () from /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so
#8  0x000000000059f9fc in _PyObject_FastCallKeywords ()
```

Versions used
```
python-hpilo==4.3
python-ilorest-library==3.0.0
ilorest-3.0.0-8_amd64.deb
ubuntu 18.04
```

The application ran on a server model ProLiant_DL380_Gen9.

**Comment by rajeevkallur** [comment]
Hi tbabamuratov,

Thanks for submitting the issue. We need more information on this.
Please let us know the scenarion you are trying and the script you are trying.  Also, from the logs, it seems like you are running it in local mode using chif channel on ubuntu 18.04.   Please zip all the content you are trying so that we can reproduce here and give you the solution.
Thanks!

**Comment by sagar-annigeri** [comment]
Can you please check with the latest version, it is working fine.
