### ISSUE TITLE
get_LogicalDrives.py generates a traceback

### ISSUE THREAD

**Issue by cvoltz** [HewlettPackard/python-ilorest-library#96]
Running the `get_LogicalDrives.py` example on an HPE Apollo 4200 generates a traceback:
```
# python3 get_LogicalDrives.py https://r12-a4200-1-ilo.dev.net Administrator password
Generation is  5
        Found resource directory at /redfish/v1/resourcedirectory

/redfish/v1/Systems/1/SmartStorage/ArrayControllers/
Logical Drive URIs for Smart Storage Array Controller '0' :
        Logical drives are not available for this controller.
Logical Drive URIs for Smart Storage Array Controller '2' :
         An associated logical drive: {'@odata.id': '/redfish/v1/Systems/1/SmartStorage/ArrayControllers/2/LogicalDrives/1/'}
Traceback (most recent call last):
  File "get_LogicalDrives.py", line 134, in <module>
    get_SmartArray_LogicalDrives(REDFISHOBJ)
  File "get_LogicalDrives.py", line 68, in get_SmartArray_LogicalDrives
    drive_data = _redfishobj.get(drives).dict
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line 108, in get
    headers=self._get_req_headers(headers=headers))
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/connections.py", line 140, in rest_request
    reqpath = path.replace('//', '/') if not external_uri else path
AttributeError: 'dict' object has no attribute 'replace'
```
I ran the test with `python-ilorest-library` version 3.0.0 on CentOS 8.2.2004 with Python 3.6.8. I get the same response with Python 2.7.17.

For reference:
```
# curl --insecure --location --silent --user Administrator:password \
https://r12-a4200-1-ilo.dev.net/redfish/v1/Systems/1/SmartStorage/ArrayControllers/2/LogicalDrives/1/ | jq .
{
  "@odata.context": "/redfish/v1/$metadata#HpeSmartStorageLogicalDrive.HpeSmartStorageLogicalDrive",
  "@odata.etag": "W/\"8ECB35D5\"",
  "@odata.id": "/redfish/v1/Systems/1/SmartStorage/ArrayControllers/2/LogicalDrives/1/",
  "@odata.type": "#HpeSmartStorageLogicalDrive.v2_3_0.HpeSmartStorageLogicalDrive",
  "Id": "1",
  "AccelerationMethod": "None",
  "CapacityMiB": 457830,
  "Description": "HPE Smart Storage Logical Drive View",
  "InterfaceType": "SATA",
  "LegacyBootPriority": "None",
  "Links": {
    "DataDrives": {
      "@odata.id": "/redfish/v1/Systems/1/SmartStorage/ArrayControllers/2/LogicalDrives/1/DataDrives/"
    }
  },
  "LogicalDriveEncryption": false,
  "LogicalDriveName": "02392989PFJHD0ARCCS0GJ 2DEA",
  "LogicalDriveNumber": 1,
  "LogicalDriveStatusReasons": [
    "Ok"
  ],
  "LogicalDriveType": "Data",
  "MediaType": "SSD",
  "Name": "HpeSmartStorageLogicalDrive",
  "Raid": "1",
  "Status": {
    "Health": "OK",
    "State": "Enabled"
  },
  "StripeSizeBytes": 262144,
  "VolumeUniqueIdentifier": "600508B1001CF0927913F12FA09F87B1"
}
```
and (after removing most of the blank lines):
```
# ssacli controller all show config

HPE Smart Array E208i-a SR Gen10 in Slot 0 (Embedded)  (sn: PWDRD0DRHD70RU)
   Apollo 4200 LFF  at Port 1I, Box 1, OK
   Apollo 4200 LFF  at Port 2I, Box 1, OK
   Port Name: 1I (Mixed)
   Port Name: 2I (Mixed)
   Unassigned
      physicaldrive 1I:1:1 (port 1I:box 1:bay 1, SAS HDD, 6 TB, OK)
      physicaldrive 1I:1:2 (port 1I:box 1:bay 2, SAS HDD, 6 TB, OK)
      physicaldrive 1I:1:3 (port 1I:box 1:bay 3, SAS HDD, 6 TB, OK)
   Enclosure SEP (Vendor ID HPE, Model Apollo 4200 LFF) 375  (WWID: 50014380439DA93C, Port: 2I, Box: 1)
   Enclosure SEP (Vendor ID HPE, Model Apollo 4200 LFF) 376  (WWID: 5001438043A3E8BC, Port: 1I, Box: 1)
   Expander 377  (WWID: 50014380439DA93D, Port: 2I, Box: 1)
   Expander 378  (WWID: 5001438043A3E8BD, Port: 1I, Box: 1)
   SEP (Vendor ID HPE, Model Smart Adapter) 379  (WWID: 51402EC014770038, Port: Unknown)

HPE Smart Array P408i-p SR Gen10 in Slot 2  (sn: PFJHD0ARCCS0GJ)
   Internal Drive Cage at Port 1I, Box 1, OK
   Internal Drive Cage at Port 2I, Box 0, OK
   Port Name: 1I (Mixed)
   Port Name: 2I (Mixed)
   Array A (Solid State SATA, Unused Space: 0  MB)
      logicaldrive 1 (447.10 GB, RAID 1, OK)
      physicaldrive 1I:1:50 (port 1I:box 1:bay 50, SATA SSD, 480 GB, OK)
      physicaldrive 1I:1:51 (port 1I:box 1:bay 51, SATA SSD, 480 GB, OK)
   Unassigned
      physicaldrive 1I:1:49 (port 1I:box 1:bay 49, SAS SSD, 800 GB, OK)
   SEP (Vendor ID HPE, Model Smart Adapter) 379  (WWID: 51402EC01370C528, Port: Unknown)
```

**Comment by vitusyu** [comment]
I also bumped into exactly same error on a DL360 Gen10 server, using Python 3.8,

root@pluto:~# python3 get_LogicalDrives_new.py
Generation is  5
        Found resource directory at /redfish/v1/resourcedirectory

/redfish/v1/Systems/1/SmartStorage/ArrayControllers/
Logical Drive URIs for Smart Storage Array Controller '0' :
         An associated logical drive: {'@odata.id': '/redfish/v1/Systems/1/SmartStorage/ArrayControllers/0/LogicalDrives/1/'}
Traceback (most recent call last):
  File "get_LogicalDrives_new.py", line 138, in <module>
    get_SmartArray_LogicalDrives(REDFISHOBJ)
  File "get_LogicalDrives_new.py", line 68, in get_SmartArray_LogicalDrives
    drive_data = _redfishobj.get(drives).dict
  File "/usr/local/lib/python3.8/dist-packages/redfish/rest/v1.py", line 107, in get
    return self.connection.rest_request(path, method='GET', args=args, \
  File "/usr/local/lib/python3.8/dist-packages/redfish/rest/connections.py", line 140, in rest_request
    reqpath = path.replace('//', '/') if not external_uri else path
AttributeError: 'dict' object has no attribute 'replace'
root@pluto:~#

**Comment by sagar-annigeri** [comment]
We have fixed in the new version of python library - python-redfish-library(3.2).
root:~# python3 get_logical_drive.py -i URL -u username -p password.
('Generation is ', u'5')
        Found resource directory at /redfish/v1/resourcedirectory

/redfish/v1/Systems/1/SmartStorage/ArrayControllers/
Logical Drive URIs for Smart Storage Array Controller '0' :
         An associated logical drive: HpeSmartStorageLogicalDrives
{
    "@odata.context": "/redfish/v1/$metadata#HpeSmartStorageLogicalDrive.HpeSmartStorageLogicalDrive",
    "@odata.etag": "W/\"0424018B\"",
    "@odata.id": "/redfish/v1/Systems/1/SmartStorage/ArrayControllers/0/LogicalDrives/1/",
    "@odata.type": "#HpeSmartStorageLogicalDrive.v2_3_0.HpeSmartStorageLogicalDrive",
    "AccelerationMethod": "ControllerCache",
    "CapacityMiB": 1907674,
    "Description": "HPE Smart Storage Logical Drive View",
    "Id": "1",
    "InterfaceType": "SATA",
    "LegacyBootPriority": "None",
    "Links": {
        "DataDrives": {
            "@odata.id": "/redfish/v1/Systems/1/SmartStorage/ArrayControllers/0/LogicalDrives/1/DataDrives/"
        }
    },
    "LogicalDriveEncryption": false,
    "LogicalDriveName": "Logical Drive 1_sunitha",
    "LogicalDriveNumber": 1,
    "LogicalDriveStatusReasons": [
        "Ok"
    ],
    "LogicalDriveType": "Data",
    "MediaType": "HDD",
    "Name": "HpeSmartStorageLogicalDrive",
    "Raid": "0",
    "Status": {
        "Health": "OK",
        "State": "Enabled"
    },
    "StripeSizeBytes": 262144,
    "VolumeUniqueIdentifier": "600508B1001C549798BE870172F59722"
}

**Comment by rajeevkallur** [comment]
Please let us know if we can close this issue

**Comment by cvoltz** [comment]
Just using the download file as you suggested, didn't work:
```bash
$ wget --quiet https://raw.githubusercontent.com/HewlettPackard/python-ilorest-library/master/examples/Redfish/get_logical_drives.py
                                                                                                                                  
$ pip3 install --user python-ilorest-library
Collecting python-ilorest-library
  Using cached https://files.pythonhosted.org/packages/55/90/f46b24bea0930e482fc22e4c6048caf400c4ca673180432bbd4a3faa47bd/python-ilorest-library-3.1.0.zip
Collecting jsonpatch (from python-ilorest-library)
  Using cached https://files.pythonhosted.org/packages/4f/d0/34b0f59ac08de9c1e07876cfecd80aec650600177b4bd445124c755499a7/jsonpatch-1.26-py2.py3-none-any.whl
Collecting jsonpath_rw (from python-ilorest-library)
  Using cached https://files.pythonhosted.org/packages/71/7c/45001b1f19af8c4478489fbae4fc657b21c4c669d7a5a036a86882581d85/jsonpath-rw-1.4.0.tar.gz
Collecting jsonpointer (from python-ilorest-library)
  Downloading https://files.pythonhosted.org/packages/18/b0/a80d29577c08eea401659254dfaed87f1af45272899e1812d7e01b679bc5/jsonpointer-2.0-py2.py3-none-any.whl
Requirement already satisfied: urllib3 in /usr/lib/python3.6/site-packages (from python-ilorest-library)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from python-ilorest-library)
Collecting ply (from jsonpath_rw->python-ilorest-library)
  Downloading https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 585kB/s
Collecting decorator (from jsonpath_rw->python-ilorest-library)
  Downloading https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Installing collected packages: jsonpointer, jsonpatch, ply, decorator, jsonpath-rw, python-ilorest-library
  Running setup.py install for jsonpath-rw ... done
  Running setup.py install for python-ilorest-library ... done
Successfully installed decorator-4.4.2 jsonpatch-1.26 jsonpath-rw-1.4.0 jsonpointer-2.0 ply-3.11 python-ilorest-library-3.1.0
                                                                                                                
$ python3 get_logical_drives.py https://r12-a4200-1-ilo.dev.net Administrator password
Traceback (most recent call last):
  File "get_logical_drives.py", line 25, in <module>
    from ilorest_util import get_resource_directory
ModuleNotFoundError: No module named 'ilorest_util'
```

So then I tried cloning the repo and running:
```bash
$ git clone https://github.com/HewlettPackard/python-ilorest-library.git
Cloning into 'python-ilorest-library'...
warning: templates not found in /home/cvoltz/.git_template
remote: Enumerating objects: 220, done.
remote: Counting objects: 100% (220/220), done.
remote: Compressing objects: 100% (179/179), done.
remote: Total 1521 (delta 122), reused 90 (delta 39), pack-reused 1301
Receiving objects: 100% (1521/1521), 2.96 MiB | 7.25 MiB/s, done.
Resolving deltas: 100% (1031/1031), done.

$ cd python-ilorest-library/examples/Redfish/

$ python3 get_logical_drives.py -i https://r12-a4200-1-ilo.dev.net -u Administrator -p password
https://https://r12-a4200-1-ilo.dev.net
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 348, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f5d971e6f60>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cvoltz/.local/lib/python3.6/site-packages/redfish/rest/connections.py", line 225, in rest_request
    resp = self._conn(method, reqfullpath, **request_args)
  File "/usr/lib/python3.6/site-packages/urllib3/request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/lib/python3.6/site-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 762, in urlopen
    **response_kw
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 762, in urlopen
    **response_kw
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 762, in urlopen
    **response_kw
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //r12-a4200-1-ilo.dev.net/redfish/v1/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5d971e6f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_logical_drives.py", line 136, in <module>
    redfish_obj.login()
  File "/home/cvoltz/.local/lib/python3.6/site-packages/redfish/rest/v1.py", line 321, in login
    self._get_root()
  File "/home/cvoltz/.local/lib/python3.6/site-packages/redfish/rest/v1.py", line 347, in _get_root
    resp = self.get(self.default_prefix)
  File "/home/cvoltz/.local/lib/python3.6/site-packages/redfish/rest/v1.py", line 109, in get
    headers=self._get_req_headers(headers=headers))
  File "/home/cvoltz/.local/lib/python3.6/site-packages/redfish/rest/connections.py", line 228, in rest_request
    raise RetriesExhaustedError()
redfish.rest.connections.RetriesExhaustedError
```

I can reach the machine OK:
```bash
$ ping -c1 r12-a4200-1-ilo.dev.net
PING r12-a4200-1-ilo.dev.net (192.168.120.102) 56(84) bytes of data.
64 bytes from r12-a4200-1-ilo.dev.net (192.168.120.102): icmp_seq=1 ttl=255 time=0.208 ms

--- r12-a4200-1-ilo.dev.net ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.208/0.208/0.208/0.000 ms

$ curl --head --insecure --location --silent --user Administrator:hpinvent https://r12-a4200-1-ilo.dev.n
et/redfish/v1/Systems/1/SmartStorage/ArrayControllers/2/LogicalDrives/1/
HTTP/1.1 200 OK
Allow: GET, HEAD
Content-Length: 0
Date: Wed, 21 Oct 2020 15:15:34 GMT
ETag: W/"8ECB35D5"
Link: </redfish/v1/SchemaStore/en/HpeSmartStorageLogicalDrive.json/>; rel=describedby
OData-Version: 4.0
X-Frame-Options: sameorigin

$ python3 --version
Python 3.6.8
                                                                                                                                  
$ cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)

$ env | grep -i proxy

$
```
Looking at the crash dump, I can see `https://https://r12-a4200-1-ilo.dev.net` so I looked through the code and found that the "URL" in your example isn't really a URL since the code takes that parameter and always prefixes the protocol `https://` to it before using it so I tried again with just the machine name:
```bash
$ python3 get_logical_drives.py -i r12-a4200-1-ilo.dev.net -u Administrator -p password
https://r12-a4200-1-ilo.dev.net
Generation is  5
        Found resource directory at /redfish/v1/resourcedirectory

/redfish/v1/Systems/1/SmartStorage/ArrayControllers/
Logical Drive URIs for Smart Storage Array Controller '0' :
        Logical drives are not available for this controller.
Logical Drive URIs for Smart Storage Array Controller '2' :
         An associated logical drive: HpeSmartStorageLogicalDrives
{
    "@odata.context": "/redfish/v1/$metadata#HpeSmartStorageLogicalDrive.HpeSmartStorageLogicalDrive",
    "@odata.etag": "W/\"8ECB35D5\"",
    "@odata.id": "/redfish/v1/Systems/1/SmartStorage/ArrayControllers/2/LogicalDrives/1/",
    "@odata.type": "#HpeSmartStorageLogicalDrive.v2_3_0.HpeSmartStorageLogicalDrive",
    "AccelerationMethod": "None",
    "CapacityMiB": 457830,
    "Description": "HPE Smart Storage Logical Drive View",
    "Id": "1",
    "InterfaceType": "SATA",
    "LegacyBootPriority": "None",
    "Links": {
        "DataDrives": {
            "@odata.id": "/redfish/v1/Systems/1/SmartStorage/ArrayControllers/2/LogicalDrives/1/DataDrives/"
        }
    },
    "LogicalDriveEncryption": false,
    "LogicalDriveName": "02392989PFJHD0ARCCS0GJ 2DEA",
    "LogicalDriveNumber": 1,
    "LogicalDriveStatusReasons": [
        "Ok"
    ],
    "LogicalDriveType": "Data",
    "MediaType": "SSD",
    "Name": "HpeSmartStorageLogicalDrive",
    "Raid": "1",
    "Status": {
        "Health": "OK",
        "State": "Enabled"
    },
    "StripeSizeBytes": 262144,
    "VolumeUniqueIdentifier": "600508B1001CF0927913F12FA09F87B1"
}
```

Looks like it is working now so we can close the issue. Thanks.
